[project]
name = "hw06-project"
version = "0.1.0"
description = "Проект для HW06"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
]

[tool.uv]
