[project]
name = "eda-cli"
version = "0.1.0"
description = "Mini CLI for EDA"
dependencies = [
    "pandas",
    "matplotlib",
    "typer",
    "pytest",  # Для тестов
    "jupyter>=1.1.1",
]

[project.scripts]
eda-cli = "eda_cli.cli:main"
